services:
  postgres:
    image: postgres:15-alpine3.17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}     
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"       
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0     # Последняя стабильная версия MongoDB
    container_name: mongodb-container
    ports:
      - "27017:27017"    # Пробрасываем порт для доступа из хоста
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${POSTGRES_USER}     # Имя пользователя для админ-доступа
      MONGO_INITDB_ROOT_PASSWORD: ${POSTGRES_PASSWORD} # Пароль для админ-доступа
    volumes:
      - mongodb_data:/data/db  # Персистентное хранилище для данных

volumes:
  pgdata:
  mongodb_data:
