version: '3'

vars:
  LOCAL_BIN: "{{.CURDIR}}/bin"

dotenv:
  - '.env'

tasks:
  install_deps:
    desc: "Установка утилит"
    cmds:
      - "GOBIN={{.LOCAL_BIN}} go install github.com/pressly/goose/v3/cmd/goose@v3.14.0"
      - "GOBIN={{.LOCAL_BIN}} go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1"
      - "GOBIN={{.LOCAL_BIN}} go install -mod=mod google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2"

  get_deps:
    cmds:
      - "go get -u google.golang.org/protobuf/cmd/protoc-gen-go"
      - "go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc"

  generate_note_api:
    cmds:
      - "mkdir -p pkg/note"
      - "protoc --proto_path internal/controller/grpc \
        --go_out=pkg/note --go_opt=paths=source_relative \
        --plugin=protoc-gen-go=bin/protoc-gen-go \
        --go-grpc_out=pkg/note --go-grpc_opt=paths=source_relative \
        --plugin=protoc-gen-go-grpc=bin/protoc-gen-go-grpc \
        internal/controller/grpc/note.proto"

  local_migration_status:
    cmds:
      - "{{.LOCAL_BIN}}/goose -dir {{.LOCAL_MIGRATION_DIR}} postgres {{.LOCAL_MIGRATION_DSN}} status -v"

  local_migration_up:
    cmds:
      - "{{.LOCAL_BIN}}/goose -dir {{.LOCAL_MIGRATION_DIR}} postgres {{.LOCAL_MIGRATION_DSN}} up -v"

  local_migration_down:
    cmds:
      - "{{.LOCAL_BIN}}/goose -dir {{.LOCAL_MIGRATION_DIR}} postgres {{.LOCAL_MIGRATION_DSN}} down -v"
